---

- name: Sync root-cert-chain
  uri:
    url: https://{{ansible_host}}/dataservice/system/device/sync/rootcertchain
    method: GET
    validate_certs: no
    headers:
      Cookie: "{{login.set_cookie}}"
      Content-Type: "application/json"
  register: vManage_root_cert_chain_status

