---
- set_fact:
    ALL_VIPTELA_LIST: "{{ ALL_VIPTELA_LIST | default([]) }} + [{'HOST': '{{ item }}', 'IP': '{{ hostvars[item].VPN512_INTERFACES.eth0.IP_ADDR }}'}]"
    cacheable: yes
  loop: "{{ groups.Viptela }}"
- name: copy rootCA.crt to the vepleta 
  raw: 'scp /tmp/root-ca-chain.crt admin@{{ item.IP }}:'
  loop: "{{ ALL_VIPTELA_LIST }}"
