---

- name: configure system
  cli_command:
    command: "{{ item }}"
  loop:
    - config
    - system
    - 'host-name "{{HOST_NAME}}"'
    - system-ip "{{SYSTEM_IP}}"
    - site-id "{{SITE_ID}}"
    - sp-organization-name "{{SP_ORGANIZATION_NAME}}"
    - organization-name "{{ORGANIZATION_NAME}}"
    - clock timezone "{{CLOCK_TIMEZONE}}"
    - vbond "{{VBOND_ADDRESS}}"
    - ntp server "{{NTP_SERVER}}"
    - top
    - commit
