---
- set_fact:
    ALL_VIPTELA_LIST: "{{ALL_VIPTELA_LIST|default([])}} + [{'HOST': '{{item}}', 'IP': '{{hostvars[item].VPN512_INTERFACES.eth0.IP_ADDR}}'}]"
  loop: "{{groups.Viptela}}"
- name: copy SSL_CRT to the viptela device
  raw: 'scp /tmp/{{item.HOST}}.crt admin@{{item.IP}}:'
  loop: "{{ALL_VIPTELA_LIST}}"
  delegate_to: localhost
