---
HOST_NAME: "TEST_vSmart_01"
SYSTEM_IP: 19.0.3.7
VPN0_INTERFACES:
  eth1:
    TUNNEL_FLAG: True
    IP_ADDR: 12.0.1.12
    PREFIX: 24
    PORT_STATE: "no shutdown"
    COLOR: "default"
    SERVICE: "all dhcp dns icmp sshd netconf ntp"
    NEXT_HOP: 12.0.1.254
VPN512_INTERFACES:
  eth0:
    IP_ADDR: 10.124.112.215
    PREFIX: 24
    PORT_STATE: "no shutdown"
    NEXT_HOP: 10.124.112.254


